import Head from 'next/head'
import React from 'react'
import Header from '../Header'
import Footer from '../Footer'

interface props {
  children: JSX.Element
}

const Layout = ({children} : props) => {
  return (
    <>
        <Head>
        <title>RipeBite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <>
        <Header/>
        {children}
        <Footer/>
        </>
    </>
  )
}

export default Layout